// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/api/v1beta1/api.proto

package apiv1beta1 // import "github.com/socketfunc/colony/proto/api/v1beta1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import config "github.com/socketfunc/colony/proto/config"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7d70ed10946ac868, []int{0}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GetConfigResponse struct {
	Config               *config.Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7d70ed10946ac868, []int{1}
}
func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (dst *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(dst, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *config.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type SaveConfigRequest struct {
	Config               *config.Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveConfigRequest) Reset()         { *m = SaveConfigRequest{} }
func (m *SaveConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SaveConfigRequest) ProtoMessage()    {}
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7d70ed10946ac868, []int{2}
}
func (m *SaveConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigRequest.Unmarshal(m, b)
}
func (m *SaveConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigRequest.Marshal(b, m, deterministic)
}
func (dst *SaveConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigRequest.Merge(dst, src)
}
func (m *SaveConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SaveConfigRequest.Size(m)
}
func (m *SaveConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigRequest proto.InternalMessageInfo

func (m *SaveConfigRequest) GetConfig() *config.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type SaveConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigResponse) Reset()         { *m = SaveConfigResponse{} }
func (m *SaveConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SaveConfigResponse) ProtoMessage()    {}
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7d70ed10946ac868, []int{3}
}
func (m *SaveConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigResponse.Unmarshal(m, b)
}
func (m *SaveConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigResponse.Marshal(b, m, deterministic)
}
func (dst *SaveConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigResponse.Merge(dst, src)
}
func (m *SaveConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SaveConfigResponse.Size(m)
}
func (m *SaveConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetConfigRequest)(nil), "colony.api.v1beta1.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "colony.api.v1beta1.GetConfigResponse")
	proto.RegisterType((*SaveConfigRequest)(nil), "colony.api.v1beta1.SaveConfigRequest")
	proto.RegisterType((*SaveConfigResponse)(nil), "colony.api.v1beta1.SaveConfigResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/colony.api.v1beta1.ApiService/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, "/colony.api.v1beta1.ApiService/SaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colony.api.v1beta1.ApiService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colony.api.v1beta1.ApiService/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "colony.api.v1beta1.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ApiService_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _ApiService_SaveConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1beta1/api.proto",
}

func init() { proto.RegisterFile("proto/api/v1beta1/api.proto", fileDescriptor_api_7d70ed10946ac868) }

var fileDescriptor_api_7d70ed10946ac868 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0x04, 0xb1, 0xf5,
	0xc0, 0xa2, 0x42, 0x42, 0xc9, 0xf9, 0x39, 0xf9, 0x79, 0x95, 0x7a, 0x20, 0x11, 0xa8, 0xac, 0x94,
	0x59, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x71, 0x7e, 0x72, 0x76,
	0x6a, 0x49, 0x5a, 0x69, 0x5e, 0xb2, 0x3e, 0x44, 0xa5, 0x3e, 0xc4, 0xb4, 0xe4, 0xfc, 0xbc, 0xb4,
	0xcc, 0x74, 0x28, 0x05, 0x31, 0x4b, 0xc9, 0x80, 0x4b, 0xc0, 0x3d, 0xb5, 0xc4, 0x19, 0x2c, 0x14,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc3, 0xc5, 0x99, 0x97, 0x98, 0x9b, 0x5a, 0x5c,
	0x90, 0x98, 0x9c, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x10, 0x50, 0x72, 0xe2, 0x12,
	0x44, 0xd2, 0x51, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xa4, 0xcb, 0xc5, 0x06, 0x31, 0x16, 0xac,
	0x9e, 0xdb, 0x48, 0x54, 0x0f, 0xea, 0x46, 0xa8, 0x65, 0x50, 0xe5, 0x50, 0x45, 0x20, 0x33, 0x82,
	0x13, 0xcb, 0x52, 0x51, 0xad, 0x25, 0xd1, 0x0c, 0x11, 0x2e, 0x21, 0x64, 0x33, 0x20, 0x0e, 0x31,
	0x3a, 0xcc, 0xc8, 0xc5, 0xe5, 0x58, 0x90, 0x19, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x14,
	0xc1, 0xc5, 0x09, 0x77, 0xac, 0x90, 0x8a, 0x1e, 0x66, 0xc0, 0xe9, 0xa1, 0xfb, 0x5e, 0x4a, 0x95,
	0x80, 0x2a, 0xa8, 0x8f, 0xa3, 0xb9, 0xb8, 0x10, 0xd6, 0x0b, 0x61, 0xd5, 0x84, 0xe1, 0x45, 0x29,
	0x35, 0x42, 0xca, 0x20, 0x86, 0x3b, 0x59, 0x47, 0x59, 0x12, 0x11, 0x9f, 0x48, 0xa9, 0xc3, 0x3a,
	0xb1, 0x20, 0x13, 0xca, 0x4c, 0x62, 0x03, 0xcb, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x59, 0xf4, 0x97, 0x44, 0x02, 0x00, 0x00,
}
