// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/api/v1beta1/api.proto

package api // import "github.com/socketfunc/colony/proto/api/v1beta1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import config "github.com/socketfunc/colony/proto/config"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{0}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GetConfigResponse struct {
	Config               *config.Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{1}
}
func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (dst *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(dst, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *config.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type SaveConfigRequest struct {
	Config               *config.Config `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveConfigRequest) Reset()         { *m = SaveConfigRequest{} }
func (m *SaveConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SaveConfigRequest) ProtoMessage()    {}
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{2}
}
func (m *SaveConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigRequest.Unmarshal(m, b)
}
func (m *SaveConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigRequest.Marshal(b, m, deterministic)
}
func (dst *SaveConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigRequest.Merge(dst, src)
}
func (m *SaveConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SaveConfigRequest.Size(m)
}
func (m *SaveConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigRequest proto.InternalMessageInfo

func (m *SaveConfigRequest) GetConfig() *config.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type SaveConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigResponse) Reset()         { *m = SaveConfigResponse{} }
func (m *SaveConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SaveConfigResponse) ProtoMessage()    {}
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{3}
}
func (m *SaveConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigResponse.Unmarshal(m, b)
}
func (m *SaveConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigResponse.Marshal(b, m, deterministic)
}
func (dst *SaveConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigResponse.Merge(dst, src)
}
func (m *SaveConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SaveConfigResponse.Size(m)
}
func (m *SaveConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigResponse proto.InternalMessageInfo

type GetPublicKeysRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPublicKeysRequest) Reset()         { *m = GetPublicKeysRequest{} }
func (m *GetPublicKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetPublicKeysRequest) ProtoMessage()    {}
func (*GetPublicKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{4}
}
func (m *GetPublicKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicKeysRequest.Unmarshal(m, b)
}
func (m *GetPublicKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetPublicKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicKeysRequest.Merge(dst, src)
}
func (m *GetPublicKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetPublicKeysRequest.Size(m)
}
func (m *GetPublicKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicKeysRequest proto.InternalMessageInfo

func (m *GetPublicKeysRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type GetPublicKeysResponse struct {
	Keys                 []*PublicKey `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPublicKeysResponse) Reset()         { *m = GetPublicKeysResponse{} }
func (m *GetPublicKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetPublicKeysResponse) ProtoMessage()    {}
func (*GetPublicKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{5}
}
func (m *GetPublicKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicKeysResponse.Unmarshal(m, b)
}
func (m *GetPublicKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetPublicKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicKeysResponse.Merge(dst, src)
}
func (m *GetPublicKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetPublicKeysResponse.Size(m)
}
func (m *GetPublicKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicKeysResponse proto.InternalMessageInfo

func (m *GetPublicKeysResponse) GetKeys() []*PublicKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

type PublicKey struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpiredAt            int64    `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3ec7a385fd5a2574, []int{6}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PublicKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PublicKey) GetExpiredAt() int64 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

func init() {
	proto.RegisterType((*GetConfigRequest)(nil), "colony.api.v1beta1.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "colony.api.v1beta1.GetConfigResponse")
	proto.RegisterType((*SaveConfigRequest)(nil), "colony.api.v1beta1.SaveConfigRequest")
	proto.RegisterType((*SaveConfigResponse)(nil), "colony.api.v1beta1.SaveConfigResponse")
	proto.RegisterType((*GetPublicKeysRequest)(nil), "colony.api.v1beta1.GetPublicKeysRequest")
	proto.RegisterType((*GetPublicKeysResponse)(nil), "colony.api.v1beta1.GetPublicKeysResponse")
	proto.RegisterType((*PublicKey)(nil), "colony.api.v1beta1.PublicKey")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	GetPublicKeys(ctx context.Context, in *GetPublicKeysRequest, opts ...grpc.CallOption) (*GetPublicKeysResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/colony.api.v1beta1.ApiService/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, "/colony.api.v1beta1.ApiService/SaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetPublicKeys(ctx context.Context, in *GetPublicKeysRequest, opts ...grpc.CallOption) (*GetPublicKeysResponse, error) {
	out := new(GetPublicKeysResponse)
	err := c.cc.Invoke(ctx, "/colony.api.v1beta1.ApiService/GetPublicKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	GetPublicKeys(context.Context, *GetPublicKeysRequest) (*GetPublicKeysResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colony.api.v1beta1.ApiService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colony.api.v1beta1.ApiService/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colony.api.v1beta1.ApiService/GetPublicKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetPublicKeys(ctx, req.(*GetPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "colony.api.v1beta1.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ApiService_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _ApiService_SaveConfig_Handler,
		},
		{
			MethodName: "GetPublicKeys",
			Handler:    _ApiService_GetPublicKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/v1beta1/api.proto",
}

func init() { proto.RegisterFile("proto/api/v1beta1/api.proto", fileDescriptor_api_3ec7a385fd5a2574) }

var fileDescriptor_api_3ec7a385fd5a2574 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x89, 0x11, 0x21, 0xcf, 0x5d, 0x70, 0x07, 0x85, 0x90, 0x5d, 0x21, 0x84, 0xdd, 0x25,
	0x7b, 0xd8, 0x64, 0xcd, 0x4a, 0x2f, 0x3d, 0x69, 0x0f, 0x42, 0x7b, 0x91, 0x78, 0x29, 0xed, 0xa1,
	0x24, 0xe3, 0xd3, 0x0e, 0xd1, 0x4c, 0x6a, 0x26, 0xd2, 0xfc, 0x49, 0xfd, 0x2f, 0x4b, 0x92, 0xc1,
	0xdf, 0x45, 0x7b, 0xca, 0xe3, 0x9b, 0xcf, 0xfb, 0xbe, 0x5f, 0x0c, 0x7c, 0x4f, 0x56, 0x5c, 0x70,
	0x37, 0x48, 0x98, 0xbb, 0xee, 0x85, 0x28, 0x82, 0x5e, 0x11, 0x3b, 0xa5, 0x4a, 0x08, 0xe5, 0x0b,
	0x1e, 0xe7, 0x4e, 0xa1, 0xc8, 0xbf, 0xc6, 0xd5, 0x9c, 0x89, 0xe7, 0x2c, 0x74, 0x28, 0x5f, 0xba,
	0x29, 0xa7, 0x11, 0x8a, 0x59, 0x16, 0x53, 0xb7, 0x22, 0xdd, 0xca, 0x8d, 0xf2, 0x78, 0xc6, 0xe6,
	0xf2, 0x53, 0x79, 0x59, 0xff, 0xa0, 0x35, 0x42, 0x71, 0x53, 0x4a, 0x3e, 0xbe, 0x64, 0x98, 0x0a,
	0xf2, 0x03, 0xb4, 0x38, 0x58, 0x62, 0x9a, 0x04, 0x14, 0x75, 0xc5, 0x54, 0x6c, 0xcd, 0xdf, 0x0a,
	0xd6, 0x10, 0xbe, 0xed, 0x64, 0xa4, 0x09, 0x8f, 0x53, 0x24, 0x7f, 0xa1, 0x51, 0xd9, 0x96, 0x7c,
	0xd3, 0xeb, 0x38, 0xb2, 0x47, 0x59, 0x4c, 0xe2, 0x12, 0x2a, 0x3c, 0x26, 0xc1, 0x1a, 0xf7, 0xcb,
	0x7e, 0xd2, 0xa3, 0x0d, 0x64, 0xd7, 0xa3, 0x6a, 0xc4, 0xea, 0x43, 0x7b, 0x84, 0x62, 0x9c, 0x85,
	0x0b, 0x46, 0xef, 0x30, 0x4f, 0x2f, 0x9b, 0xe9, 0x16, 0x3a, 0x07, 0x59, 0x72, 0xae, 0x1e, 0xd4,
	0x23, 0xcc, 0x53, 0x5d, 0x31, 0x55, 0xbb, 0xe9, 0x75, 0x9d, 0xe3, 0xcd, 0x3b, 0x9b, 0x2c, 0xbf,
	0x44, 0xad, 0x31, 0x68, 0x1b, 0x89, 0x10, 0xa8, 0x47, 0x2c, 0x9e, 0xca, 0x8a, 0x65, 0x4c, 0x5a,
	0xa0, 0x46, 0x98, 0xeb, 0x35, 0x53, 0xb1, 0xbf, 0xf8, 0x45, 0x48, 0xba, 0x00, 0xf8, 0x9a, 0xb0,
	0x15, 0x4e, 0x9f, 0x02, 0xa1, 0xab, 0xa6, 0x62, 0xab, 0xbe, 0x26, 0x95, 0x81, 0xf0, 0xde, 0x6a,
	0x00, 0x83, 0x84, 0x4d, 0x70, 0xb5, 0x66, 0x14, 0xc9, 0x3d, 0x68, 0x9b, 0x03, 0x90, 0x9f, 0xa7,
	0x5a, 0x3a, 0xbc, 0xa8, 0xf1, 0xeb, 0x0c, 0x25, 0xa7, 0x7d, 0x04, 0xd8, 0xae, 0x94, 0x9c, 0x4c,
	0x3a, 0x3a, 0x9b, 0xf1, 0xfb, 0x1c, 0x26, 0xcd, 0xa7, 0xf0, 0x75, 0x6f, 0xc7, 0xc4, 0xfe, 0xa0,
	0xa9, 0xa3, 0xe3, 0x19, 0x7f, 0x2e, 0x20, 0xab, 0x2a, 0xc3, 0xfe, 0x83, 0x77, 0xc1, 0x4b, 0xd8,
	0x79, 0x57, 0xd7, 0x41, 0xc2, 0xc2, 0x46, 0x29, 0xff, 0x7f, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xca,
	0x62, 0x94, 0x96, 0x77, 0x03, 0x00, 0x00,
}
