// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/config/config.proto

package config // import "github.com/socketfunc/colony/proto/config"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Version              string    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	Spec                 *Spec     `protobuf:"bytes,3,opt,name=Spec" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Config) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Config) GetSpec() *Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type Metadata struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string            `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Spec struct {
	Functions            []*Function `protobuf:"bytes,1,rep,name=functions" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
func (*Spec) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{2}
}
func (m *Spec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spec.Unmarshal(m, b)
}
func (m *Spec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spec.Marshal(b, m, deterministic)
}
func (dst *Spec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spec.Merge(dst, src)
}
func (m *Spec) XXX_Size() int {
	return xxx_messageInfo_Spec.Size(m)
}
func (m *Spec) XXX_DiscardUnknown() {
	xxx_messageInfo_Spec.DiscardUnknown(m)
}

var xxx_messageInfo_Spec proto.InternalMessageInfo

func (m *Spec) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

type Function struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repository           string     `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Resources            *Resources `protobuf:"bytes,3,opt,name=resources" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{3}
}
func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (dst *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(dst, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Function) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Function) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Resources struct {
	Requests             *Requests `protobuf:"bytes,1,opt,name=requests" json:"requests,omitempty"`
	Limits               *Limits   `protobuf:"bytes,2,opt,name=limits" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{4}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetRequests() *Requests {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *Resources) GetLimits() *Limits {
	if m != nil {
		return m.Limits
	}
	return nil
}

type Requests struct {
	Timeout              string   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requests) Reset()         { *m = Requests{} }
func (m *Requests) String() string { return proto.CompactTextString(m) }
func (*Requests) ProtoMessage()    {}
func (*Requests) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{5}
}
func (m *Requests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requests.Unmarshal(m, b)
}
func (m *Requests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requests.Marshal(b, m, deterministic)
}
func (dst *Requests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requests.Merge(dst, src)
}
func (m *Requests) XXX_Size() int {
	return xxx_messageInfo_Requests.Size(m)
}
func (m *Requests) XXX_DiscardUnknown() {
	xxx_messageInfo_Requests.DiscardUnknown(m)
}

var xxx_messageInfo_Requests proto.InternalMessageInfo

func (m *Requests) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type Limits struct {
	Requests             int32    `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Limits) Reset()         { *m = Limits{} }
func (m *Limits) String() string { return proto.CompactTextString(m) }
func (*Limits) ProtoMessage()    {}
func (*Limits) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_5c8026477ccacdc5, []int{6}
}
func (m *Limits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limits.Unmarshal(m, b)
}
func (m *Limits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limits.Marshal(b, m, deterministic)
}
func (dst *Limits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limits.Merge(dst, src)
}
func (m *Limits) XXX_Size() int {
	return xxx_messageInfo_Limits.Size(m)
}
func (m *Limits) XXX_DiscardUnknown() {
	xxx_messageInfo_Limits.DiscardUnknown(m)
}

var xxx_messageInfo_Limits proto.InternalMessageInfo

func (m *Limits) GetRequests() int32 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "colony.config.Config")
	proto.RegisterType((*Metadata)(nil), "colony.config.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "colony.config.Metadata.LabelsEntry")
	proto.RegisterType((*Spec)(nil), "colony.config.Spec")
	proto.RegisterType((*Function)(nil), "colony.config.Function")
	proto.RegisterType((*Resources)(nil), "colony.config.Resources")
	proto.RegisterType((*Requests)(nil), "colony.config.Requests")
	proto.RegisterType((*Limits)(nil), "colony.config.Limits")
}

func init() { proto.RegisterFile("proto/config/config.proto", fileDescriptor_config_5c8026477ccacdc5) }

var fileDescriptor_config_5c8026477ccacdc5 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0xc5, 0x71, 0xe2, 0xd9, 0x37, 0x0c, 0x86, 0xb6, 0x31, 0x2f, 0x8c, 0x11, 0xbc, 0xc0, 0x32,
	0x46, 0x6d, 0x48, 0x68, 0xe9, 0x07, 0x7d, 0x69, 0x69, 0x9f, 0xd2, 0x17, 0xf5, 0xad, 0x6f, 0x8e,
	0xaa, 0xa4, 0x22, 0xb6, 0xe5, 0x4a, 0x72, 0xc0, 0x6f, 0xfd, 0x51, 0xfd, 0x81, 0xc5, 0xb2, 0x1c,
	0xa7, 0x6e, 0xfb, 0x64, 0xdd, 0x73, 0xcf, 0xd1, 0x39, 0xba, 0xbe, 0xf0, 0x33, 0x17, 0x5c, 0xf1,
	0x88, 0xf0, 0x6c, 0xc5, 0xd6, 0xe6, 0x13, 0x6a, 0x0c, 0x7d, 0x26, 0x3c, 0xe1, 0x59, 0x19, 0xd6,
	0x60, 0xf0, 0x64, 0x81, 0x73, 0xa9, 0x8f, 0xc8, 0x87, 0x4f, 0x5b, 0x2a, 0x24, 0xe3, 0x99, 0x6f,
	0x8d, 0xad, 0xa9, 0x87, 0x9b, 0x12, 0xcd, 0xc1, 0x4d, 0xa9, 0x8a, 0xef, 0x63, 0x15, 0xfb, 0xbd,
	0xb1, 0x35, 0x1d, 0xce, 0x7e, 0x84, 0xaf, 0xae, 0x09, 0x6f, 0x4c, 0x1b, 0xef, 0x88, 0xe8, 0x2f,
	0xf4, 0x6f, 0x73, 0x4a, 0x7c, 0x5b, 0x0b, 0xbe, 0x76, 0x04, 0x55, 0x0b, 0x6b, 0x42, 0xf0, 0x6c,
	0x81, 0xdb, 0xe8, 0x11, 0x82, 0x7e, 0x16, 0xa7, 0xd4, 0x24, 0xd0, 0x67, 0xf4, 0x0b, 0xbc, 0xea,
	0x2b, 0xf3, 0x98, 0x50, 0xed, 0xef, 0xe1, 0x16, 0x40, 0x67, 0xe0, 0x24, 0xf1, 0x92, 0x26, 0xd2,
	0xb7, 0xc7, 0xf6, 0x74, 0x38, 0xfb, 0xf3, 0x41, 0xb4, 0x70, 0xa1, 0x59, 0x57, 0x99, 0x12, 0x25,
	0x36, 0x92, 0xd1, 0x09, 0x0c, 0xf7, 0x60, 0xf4, 0x05, 0xec, 0x0d, 0x2d, 0x8d, 0x79, 0x75, 0x44,
	0xdf, 0x60, 0xb0, 0x8d, 0x93, 0xa2, 0xf1, 0xad, 0x8b, 0xd3, 0xde, 0xb1, 0x15, 0x9c, 0xd7, 0xef,
	0x43, 0x87, 0xe0, 0xad, 0x8a, 0x8c, 0x28, 0xc6, 0x33, 0xe9, 0x5b, 0x3a, 0x42, 0x77, 0x3a, 0xd7,
	0xa6, 0x8f, 0x5b, 0x66, 0xb0, 0x05, 0xb7, 0x81, 0xdf, 0x7d, 0xf4, 0x6f, 0x00, 0x41, 0x73, 0x2e,
	0x99, 0xe2, 0xa2, 0x34, 0xee, 0x7b, 0x08, 0x3a, 0x02, 0x4f, 0x50, 0xc9, 0x0b, 0x41, 0xa8, 0x34,
	0x33, 0xf6, 0x3b, 0xb6, 0xb8, 0xe9, 0xe3, 0x96, 0x1a, 0x70, 0xf0, 0x76, 0x78, 0xf5, 0x63, 0x05,
	0x7d, 0x2c, 0xa8, 0x54, 0x52, 0x9b, 0xbf, 0x8d, 0x8e, 0x4d, 0x1b, 0xef, 0x88, 0xe8, 0x00, 0x9c,
	0x84, 0xa5, 0x4c, 0x49, 0xb3, 0x0b, 0xdf, 0x3b, 0x92, 0x85, 0x6e, 0x62, 0x43, 0x0a, 0x26, 0xe0,
	0x36, 0x97, 0x54, 0x2b, 0xa6, 0x58, 0x4a, 0x79, 0xa1, 0x9a, 0x15, 0x33, 0x65, 0x30, 0x01, 0xa7,
	0xd6, 0xa1, 0x51, 0x27, 0xd3, 0xa0, 0xb5, 0xbe, 0xf8, 0x7f, 0xf7, 0x6f, 0xcd, 0xd4, 0x43, 0xb1,
	0x0c, 0x09, 0x4f, 0x23, 0xc9, 0xc9, 0x86, 0xaa, 0x6a, 0xa4, 0x51, 0x9d, 0x20, 0xda, 0x5f, 0xfb,
	0xa5, 0xa3, 0xab, 0xf9, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xf7, 0x0f, 0xa0, 0x0d, 0x03,
	0x00, 0x00,
}
